import type {
  ChangeItem,
  OperatingAssetView,
  ProjectMilestone,
  ProjectView,
  SourceDetail,
} from './types';
import liveProjectsJson from './projects-live.json';

const qH: Array<readonly [string, number, number]> = [
    [`2016`, 1632742233, 445789016],
    [`2017`, 1789231275, 419451892],
    [`2018`, 2025955030, 680482295],
    [`2019`, 2425683481, 982314744],
    [`2020`, 2489186458, 1034179273],
    [`2021`, 2626904218, 1113841091],
    [`2022`, 2930162191, 1209251676],
    [`2023`, 2877189091, 1130691960],
    [`2024`, 2975719661, 1197604853],
    [`2025`, 3300921302, 1322843656],
  ],
  JH: Array<readonly [string, number, number]> = [
    [`2016`, 1445936945, 575530426],
    [`2017`, 1550411249, 622754984],
    [`2018`, 1591355249, 713242779],
    [`2019`, 1701581418, 757995913],
    [`2020`, 1647514114, 724897130],
    [`2021`, 1698327887, 744786016],
    [`2022`, 1726860305, 724805980],
    [`2023`, 1780404175, 725672332],
    [`2024`, 1874976650, 788065735],
    [`2025`, 2120467866, 900205595],
  ],
  YH = (e: string, t: string, n: string, r?: string): SourceDetail => ({
    id: e,
    title: t,
    sourceSystem: `FERC eCollection / eForms XBRL`,
    period: n,
    scope: `Filing entity, whole entity`,
    unit: `USD; throughput in FERC Dth`,
    method: n.endsWith(`Q4`)
      ? `Filed annual values with supplied Q4 derivations where noted`
      : `Filed`,
    availability: `Present`,
    origin: `FERC-migrated`,
    filingVersion: `Canonical version in reference export`,
    validation: r ? `Warning retained` : `Accepted in reference export`,
    warnings: r
      ? [r]
      : [
          `Operating income is a filed FERC accounting measure; it is not EBITDA or cash flow.`,
        ],
  }),
  XH: OperatingAssetView[] = [
    {
      id: `transco`,
      name: `Transcontinental Gas Pipe Line system`,
      company: `Williams`,
      ticker: `WMB`,
      legalFiler: `Transcontinental Gas Pipe Line Company, LLC`,
      cid: `C000029`,
      regime: `Interstate gas`,
      canonicalAssetType: `interstate_gas_transmission`,
      canonicalAssetTypeLabel: `Interstate gas transmission`,
      canonicalAssetTypeWarning: `The detached universe row for wmb-transco lists CID C000654, while this copied metric reference lists C000029. The frontend preserves both source identities and does not reconcile them.`,
      scope: `Whole filing entity; values must not be summed into a parent-company total.`,
      snapshotDate: `2026-09-08`,
      latestCopiedQuarter: `2017 Q3`,
      status: {
        availability: `present`,
        origin: `ferc_migrated`,
        method: `filed`,
        version: `original`,
        validation: `pass`,
      },
      quarters: [
        {
          period: `2016 Q1`,
          revenue: 408876101,
          income: 119609447,
          throughput: 1318750587,
          sourceId: `transco-2016q1`,
        },
        {
          period: `2016 Q2`,
          revenue: 392606175,
          income: 109619555,
          throughput: 1161429030,
          sourceId: `transco-2016q2`,
        },
        {
          period: `2016 Q3`,
          revenue: 411143191,
          income: 105607016,
          throughput: 1274082650,
          sourceId: `transco-2016q3`,
        },
        {
          period: `2016 Q4`,
          revenue: 420116766,
          income: 110952998,
          throughput: 1236064998,
          sourceId: `transco-2016q4`,
        },
        {
          period: `2017 Q1`,
          revenue: 415062808,
          income: 116577540,
          throughput: 1311310233,
          sourceId: `transco-2017q1`,
        },
        {
          period: `2017 Q2`,
          revenue: 435297916,
          income: 110488922,
          throughput: 1219692249,
          sourceId: `transco-2017q2`,
        },
        {
          period: `2017 Q3`,
          revenue: 450550900,
          income: 107109339,
          throughput: 1273735309,
          sourceId: `transco-2017q3`,
        },
      ],
      annual: qH.map(([e, t, n]) => ({ year: e, revenue: t, income: n })),
      changes: [
        {
          date: `2018-04-17`,
          title: `2017 annual filing represented in the copied sample`,
          detail: `This is historical filing archive context, not a current alert.`,
          sourceId: `transco-annual`,
        },
      ],
      sources: [
        ...[
          `2016q1`,
          `2016q2`,
          `2016q3`,
          `2016q4`,
          `2017q1`,
          `2017q2`,
          `2017q3`,
        ].map((e) =>
          YH(
            `transco-${e}`,
            `Transco ${e.toUpperCase()} filing values`,
            e.replace(/(\d{4})q(\d)/, `$1 Q$2`),
            e.endsWith(`q4`)
              ? `Q4 financial values include supplied derivation methods; exact source URL was not copied into this frontend slice.`
              : void 0,
          ),
        ),
        {
          id: `transco-annual`,
          title: `Transco annual key metrics`,
          sourceSystem: `FERC eCollection / eForms XBRL`,
          period: `2016–2025`,
          scope: `Filing entity, whole entity`,
          unit: `USD`,
          method: `Filed annual values`,
          availability: `Present`,
          origin: `FERC-migrated`,
          validation: `Accepted reference export`,
          warnings: [
            `Annual values are displayed in a separate panel and are not presented as current-quarter figures.`,
          ],
        },
      ],
    },
    {
      id: `tgp`,
      name: `Tennessee Gas Pipeline system`,
      company: `Kinder Morgan`,
      ticker: `KMI`,
      legalFiler: `Tennessee Gas Pipeline Company, L.L.C.`,
      cid: `C000020`,
      regime: `Interstate gas`,
      canonicalAssetType: `interstate_gas_transmission`,
      canonicalAssetTypeLabel: `Interstate gas transmission`,
      scope: `Whole filing entity; values must not be summed into a parent-company total.`,
      snapshotDate: `2026-09-08`,
      latestCopiedQuarter: `2017 Q4`,
      status: {
        availability: `present`,
        origin: `ferc_migrated`,
        method: `filed`,
        version: `original`,
        validation: `warning`,
      },
      quarters: [
        {
          period: `2016 Q1`,
          revenue: 391223090,
          income: 169025347,
          throughput: 875466124,
          sourceId: `tgp-2016q1`,
        },
        {
          period: `2016 Q2`,
          revenue: 341957491,
          income: 127925437,
          throughput: 807389391,
          sourceId: `tgp-2016q2`,
        },
        {
          period: `2016 Q3`,
          revenue: 344264111,
          income: 129741525,
          throughput: 824538023,
          sourceId: `tgp-2016q3`,
        },
        {
          period: `2016 Q4`,
          revenue: 368492253,
          income: 148838117,
          throughput: 802047732,
          sourceId: `tgp-2016q4`,
        },
        {
          period: `2017 Q1`,
          revenue: 390111204,
          income: 164157640,
          throughput: 908377329,
          sourceId: `tgp-2017q1`,
        },
        {
          period: `2017 Q2`,
          revenue: 377648319,
          income: 146830059,
          throughput: 835681264,
          sourceId: `tgp-2017q2`,
        },
        {
          period: `2017 Q3`,
          revenue: 373193258,
          income: 137292791,
          throughput: 834779431,
          sourceId: `tgp-2017q3`,
        },
        {
          period: `2017 Q4`,
          revenue: 409458468,
          income: 174474494,
          throughput: 872362154,
          sourceId: `tgp-2017q4`,
        },
      ],
      annual: JH.map(([e, t, n]) => ({ year: e, revenue: t, income: n })),
      changes: [
        {
          date: `2022-04-18`,
          title: `Q4 identity warning retained in source QA`,
          detail: `The supplied 2021 Q4 identity differs by $2; values remain displayed with a warning.`,
          sourceId: `tgp-annual`,
        },
      ],
      sources: [
        ...[
          `2016q1`,
          `2016q2`,
          `2016q3`,
          `2016q4`,
          `2017q1`,
          `2017q2`,
          `2017q3`,
          `2017q4`,
        ].map((e, t) => {
          const n = [
            `29097`,
            `29281`,
            `29404`,
            `29604`,
            `29722`,
            `29863`,
            `29994`,
            `30168`,
          ];
          return {
            ...YH(
              `tgp-${e}`,
              `TGP ${e.toUpperCase()} filing values`,
              e.replace(/(\d{4})q(\d)/, `$1 Q$2`),
              e.endsWith(`q4`)
                ? `Q4 financial values include supplied derivation methods.`
                : void 0,
            ),
            nativeIdentity: `Filing ID ${n[t]}`,
          };
        }),
        {
          id: `tgp-annual`,
          title: `TGP annual key metrics`,
          sourceSystem: `FERC eCollection / eForms XBRL`,
          period: `2016–2025`,
          scope: `Filing entity, whole entity`,
          unit: `USD`,
          method: `Filed annual values`,
          availability: `Present`,
          origin: `FERC-migrated`,
          validation: `Accepted with retained QA notes`,
          warnings: [
            `The repaired generalisation package retains a $2 identity warning for 2021 Q4.`,
          ],
        },
      ],
    },
    {
      id: `elba-express`,
      name: `Elba Express`,
      company: `Kinder Morgan`,
      ticker: `KMI`,
      legalFiler: `Elba Express Company, L.L.C.`,
      cid: `C000147`,
      regime: `Interstate gas`,
      canonicalAssetType: `interstate_gas_transmission`,
      canonicalAssetTypeLabel: `Interstate gas transmission`,
      scope: `Whole filing entity in the reviewed operating-asset universe; operating histories were not copied into this frontend snapshot.`,
      snapshotDate: `2026-09-08`,
      latestCopiedQuarter: `Not retrieved`,
      status: {
        availability: `not_retrieved`,
        origin: `backend_assessment`,
        method: `backend_assessment`,
        version: `original`,
        validation: `pass`,
      },
      quarters: [],
      annual: [],
      changes: [],
      sources: [
        {
          id: `elba-express-universe`,
          title: `Elba Express reviewed asset mapping`,
          sourceSystem: `Detached operating-asset universe`,
          nativeIdentity: `kmi-elba-express · C000147`,
          period: `Snapshot copied 8 Sep 2026`,
          scope: `Whole filing entity`,
          method: `Reviewed identity and canonical type mapping`,
          availability: `Identity present; metrics not retrieved`,
          origin: `Backend assessment`,
          validation: `Accepted mapping`,
          warnings: [
            `No operating values were copied for this asset; blank comparison cells are not zero.`,
          ],
        },
      ],
    },
    {
      id: `transcolorado`,
      name: `TransColorado`,
      company: `Kinder Morgan`,
      ticker: `KMI`,
      legalFiler: `TransColorado Gas Transmission Company LLC`,
      cid: `C000596`,
      regime: `Interstate gas`,
      canonicalAssetType: `interstate_gas_transmission`,
      canonicalAssetTypeLabel: `Interstate gas transmission`,
      scope: `Whole filing entity in the reviewed operating-asset universe; operating histories were not copied into this frontend snapshot.`,
      snapshotDate: `2026-09-08`,
      latestCopiedQuarter: `Not retrieved`,
      status: {
        availability: `not_retrieved`,
        origin: `backend_assessment`,
        method: `backend_assessment`,
        version: `original`,
        validation: `pass`,
      },
      quarters: [],
      annual: [],
      changes: [],
      sources: [
        {
          id: `transcolorado-universe`,
          title: `TransColorado reviewed asset mapping`,
          sourceSystem: `Detached operating-asset universe`,
          nativeIdentity: `kmi-transcolorado · C000596`,
          period: `Snapshot copied 8 Sep 2026`,
          scope: `Whole filing entity`,
          method: `Reviewed identity and canonical type mapping`,
          availability: `Identity present; metrics not retrieved`,
          origin: `Backend assessment`,
          validation: `Accepted mapping`,
          warnings: [
            `No operating values were copied for this asset; blank comparison cells are not zero.`,
          ],
        },
      ],
    },
  ],
  ZH = (
    e: string,
    t: string,
    n: string,
    r: string,
    i: string,
  ): ProjectMilestone => ({
    accession: e,
    date: t,
    event_type: n,
    title: r,
    description: i,
  }),
  QH: ProjectView[] = [
    {
      project: `Southeast Supply Enhancement`,
      docket: `CP25-10`,
      current_stage: `Construction`,
      company: `Company not mapped`,
      generated_at: `2026-09-09T10:06:07.789235+00:00`,
      counts: {
        raw: 436,
        deduped: 436,
        alerts: 3,
        review: 354,
        suppressed: 79,
        activity_groups: 78,
      },
      milestones: [
        ZH(
          `20260225-3042`,
          `2026-02-25T00:00:00`,
          `construction_or_service_authorization`,
          `Construction / Service Authorization`,
          `Letter to Transcontinental Gas Pipe Line Company, LLC granting the 02/18/2026 request to commence construction of the Southeast Supply Enhancement Project under CP25-10.`,
        ),
        ZH(
          `20260129-3076`,
          `2026-01-29T00:00:00`,
          `regulatory_decision`,
          `Regulatory Decision`,
          `Order Issuing Certificate and Approving Abandonment re Transcontinental Gas Pipe Line Company, LLC's SSE Project under CP25-10.`,
        ),
        ZH(
          `20251031-3000`,
          `2025-10-31T00:00:00`,
          `environmental_milestone`,
          `Environmental Milestone`,
          `Environmental Assessment for Transcontinental Gas Pipe Line Company, LLC's Southeast Supply Enhancement Project under CP25-10.`,
        ),
      ],
      regulatory_outlook: {
        regulatory_status: `progressing`,
        tracked_ferc_requests: 8,
        responded_ferc_requests: 8,
        open_ferc_requests: 0,
        latest_material_milestone: ZH(
          `20260225-3042`,
          `2026-02-25T00:00:00`,
          `construction_or_service_authorization`,
          `Construction / Service Authorization`,
          `Letter granting the request to commence construction.`,
        ),
        schedule_watch: [
          {
            kind: `deadline_timing_uncertain`,
            request_accession: `20250924-3045`,
            request_date: `2025-09-24T00:00:00`,
            estimated_due_date: `2025-09-29T00:00:00`,
            response_date: `2025-09-30T00:00:00`,
            detail: `Sponsor response occurred after the mechanically estimated due date. This is not treated as a confirmed delay.`,
          },
          {
            kind: `deadline_timing_uncertain`,
            request_accession: `20251001-3072`,
            request_date: `2025-10-01T00:00:00`,
            estimated_due_date: `2025-10-11T00:00:00`,
            response_date: `2025-10-14T00:00:00`,
            detail: `Sponsor response occurred after the mechanically estimated due date. This is not treated as a confirmed delay.`,
          },
        ],
        progression_counts: { progressed: 8 },
        next_expected_activity: `Ongoing construction, compliance, and project-status reporting`,
        investor_summary: `Project is currently in the Construction stage. 8 explicit FERC information requests were identified; all 8 have matched sponsor responses. Latest material milestone: Construction / Service Authorization on 2026-02-25. 2 historical response timing case(s) warrant review; they are not treated as confirmed delays. Available filing evidence indicates the regulatory process is progressing.`,
      },
      activity: [
        {
          activity_type: `construction_compliance`,
          label: `Construction / Compliance`,
          start_date: `2026-09-08T00:00:00`,
          end_date: `2026-09-08T00:00:00`,
          filing_count: 1,
          event_types: { context_dependent: 1 },
          relationship: `unlinked`,
          representative_accessions: [`20260908-3005`],
          summary: `Construction/compliance activity during 08 Sep 2026: 1 filing related to project implementation and compliance.`,
        },
        {
          activity_type: `delegated_authorization`,
          label: `Delegated Authorization`,
          start_date: `2026-08-17T00:00:00`,
          end_date: `2026-08-17T00:00:00`,
          filing_count: 1,
          event_types: { delegated_order: 1 },
          relationship: `discrete`,
          representative_accessions: [`20260817-3020`],
          summary: `Delegated authorization activity on 17 Aug 2026: 1 filing.`,
        },
        {
          activity_type: `construction_compliance`,
          label: `Construction / Compliance`,
          start_date: `2026-08-03T00:00:00`,
          end_date: `2026-08-21T00:00:00`,
          filing_count: 6,
          event_types: { context_dependent: 6 },
          relationship: `category_plus_time`,
          representative_accessions: [
            `20260803-3004`,
            `20260807-3034`,
            `20260812-3007`,
          ],
          summary: `Construction/compliance activity during 03 Aug 2026 to 21 Aug 2026: 6 filings related to project implementation and compliance.`,
        },
        {
          activity_type: `legal`,
          label: `Legal Activity`,
          start_date: `2026-07-20T00:00:00`,
          end_date: `2026-07-20T00:00:00`,
          filing_count: 1,
          event_types: { legal_activity: 1 },
          relationship: `discrete`,
          representative_accessions: [`20260720-4001`],
          summary: `Legal activity during 20 Jul 2026: 1 filing.`,
        },
      ],
    },
    {
      project: `Southeast Compression Utility and Reliability`,
      docket: `CP25-219`,
      current_stage: `Construction`,
      company: `Company not mapped`,
      generated_at: `2026-09-09T10:35:32.224819+00:00`,
      counts: {
        raw: 66,
        deduped: 66,
        alerts: 3,
        review: 55,
        suppressed: 8,
        activity_groups: 30,
      },
      milestones: [
        ZH(
          `20260722-3014`,
          `2026-07-22T00:00:00`,
          `construction_or_service_authorization`,
          `Construction / Service Authorization`,
          `Letter to Gulf South Pipeline Company, LLC granting the 07/17/2026 request to commence construction activities at the Hinds and Tallulah Compressor Stations as part of the Southeast Compression Utility and Reliability Expansion Project under CP25-219.`,
        ),
        ZH(
          `20260416-3041`,
          `2026-04-16T00:00:00`,
          `regulatory_decision`,
          `Regulatory Decision`,
          `Order Issuing Certificate re Gulf South Pipeline Company, LLC under CP25-219.`,
        ),
        ZH(
          `20251229-3034`,
          `2025-12-29T00:00:00`,
          `environmental_milestone`,
          `Environmental Milestone`,
          `Environmental Assessment for Gulf South Pipeline Company, LLC's Southeast Compression Utility and Reliability Expansion Project under CP25-219.`,
        ),
      ],
      regulatory_outlook: null,
      activity: [
        {
          activity_type: `construction_compliance`,
          label: `Construction / Compliance`,
          start_date: `2026-08-19T00:00:00`,
          end_date: `2026-09-01T00:00:00`,
          filing_count: 2,
          event_types: { context_dependent: 2 },
          relationship: `category_plus_time`,
          representative_accessions: [`20260819-5168`, `20260901-5206`],
          summary: `Construction/compliance activity during 19 Aug 2026 to 01 Sep 2026: 2 filings related to project implementation and compliance.`,
        },
        {
          activity_type: `other`,
          label: `Other Activity`,
          start_date: `2026-08-04T00:00:00`,
          end_date: `2026-08-04T00:00:00`,
          filing_count: 1,
          event_types: { unknown: 1 },
          relationship: `unlinked`,
          representative_accessions: [`20260804-5178`],
          summary: `Project activity during 04 Aug 2026: 1 filing.`,
        },
        {
          activity_type: `construction_compliance`,
          label: `Construction / Compliance`,
          start_date: `2026-08-04T00:00:00`,
          end_date: `2026-08-04T00:00:00`,
          filing_count: 1,
          event_types: { context_dependent: 1 },
          relationship: `unlinked`,
          representative_accessions: [`20260804-5154`],
          summary: `Construction/compliance activity during 04 Aug 2026: 1 filing related to project implementation and compliance.`,
        },
        {
          activity_type: `construction_compliance`,
          label: `Construction / Compliance`,
          start_date: `2026-07-17T00:00:00`,
          end_date: `2026-07-17T00:00:00`,
          filing_count: 1,
          event_types: { context_dependent: 1 },
          relationship: `unlinked`,
          representative_accessions: [`20260717-5245`],
          summary: `Construction/compliance activity during 17 Jul 2026: 1 filing related to project implementation and compliance.`,
        },
      ],
    },
    {
      project: `Appalachian Reliability`,
      docket: `CP25-528`,
      current_stage: `Certificate`,
      company: `Company not mapped`,
      generated_at: `2026-09-09T11:09:33.515744+00:00`,
      counts: {
        raw: 95,
        deduped: 95,
        alerts: 2,
        review: 75,
        suppressed: 18,
        activity_groups: 20,
      },
      milestones: [
        ZH(
          `20260618-3080`,
          `2026-06-18T00:00:00`,
          `regulatory_decision`,
          `Regulatory Decision`,
          `Order Issuing Certificate re Eastern Gas Transmission and Storage, Inc.'s Appalachian Reliability Project under CP25-528. Commissioner Chang is concurring with a separate statement attached.`,
        ),
        ZH(
          `20260227-3021`,
          `2026-02-27T00:00:00`,
          `environmental_milestone`,
          `Environmental Milestone`,
          `Environmental Assessment for Eastern Gas Transmission and Storage, Inc.'s Appalachian Reliability Project under CP25-528.`,
        ),
      ],
      regulatory_outlook: {
        regulatory_status: `progressing`,
        tracked_ferc_requests: 9,
        responded_ferc_requests: 9,
        open_ferc_requests: 0,
        latest_material_milestone: ZH(
          `20260618-3080`,
          `2026-06-18T00:00:00`,
          `regulatory_decision`,
          `Regulatory Decision`,
          `Order Issuing Certificate.`,
        ),
        schedule_watch: [
          {
            kind: `deadline_timing_uncertain`,
            request_accession: `20260105-3037`,
            request_date: `2026-01-05T00:00:00`,
            estimated_due_date: `2026-01-10T00:00:00`,
            response_date: `2026-01-12T00:00:00`,
            detail: `Sponsor response occurred after the mechanically estimated due date. This is not treated as a confirmed delay.`,
          },
        ],
        progression_counts: { progressed: 9 },
        next_expected_activity: `Project activity associated with the next implementation stage`,
        investor_summary: `Project is currently in the Certificate stage. 9 explicit FERC information requests were identified; all 9 have matched sponsor responses. Latest material milestone: Regulatory Decision on 2026-06-18. 1 historical response timing case(s) warrant review; they are not treated as confirmed delays. Available filing evidence indicates the regulatory process is progressing.`,
      },
      activity: [
        {
          activity_type: `construction_compliance`,
          label: `Construction / Compliance`,
          start_date: `2026-08-18T00:00:00`,
          end_date: `2026-08-28T00:00:00`,
          filing_count: 3,
          event_types: { context_dependent: 3 },
          relationship: `category_plus_time`,
          representative_accessions: [
            `20260818-5117`,
            `20260818-5116`,
            `20260828-5059`,
          ],
          summary: `Construction/compliance activity during 18 Aug 2026 to 28 Aug 2026: 3 filings related to project implementation and compliance.`,
        },
        {
          activity_type: `other`,
          label: `Other Activity`,
          start_date: `2026-07-10T00:00:00`,
          end_date: `2026-07-10T00:00:00`,
          filing_count: 1,
          event_types: { unknown: 1 },
          relationship: `unlinked`,
          representative_accessions: [`20260710-5207`],
          summary: `Project activity during 10 Jul 2026: 1 filing.`,
        },
        {
          activity_type: `other`,
          label: `Other Activity`,
          start_date: `2026-07-02T00:00:00`,
          end_date: `2026-07-02T00:00:00`,
          filing_count: 1,
          event_types: { unknown: 1 },
          relationship: `unlinked`,
          representative_accessions: [`20260702-5050`],
          summary: `Project activity during 02 Jul 2026: 1 filing.`,
        },
        {
          activity_type: `stakeholder_activity`,
          label: `Stakeholder Activity`,
          start_date: `2026-03-05T00:00:00`,
          end_date: `2026-03-23T00:00:00`,
          filing_count: 6,
          event_types: { third_party_comment: 6 },
          relationship: `bounded_phase`,
          representative_accessions: [
            `20260305-5116`,
            `20260305-5267`,
            `20260309-5004`,
          ],
          summary: `Stakeholder activity during 05 Mar 2026 to 23 Mar 2026: 6 stakeholder comments.`,
        },
      ],
    },
  ],
  $H = (e: ProjectView, t: string, n: string, r?: string): SourceDetail => ({
    id: `${e.docket}-${t}`,
    title: n,
    sourceSystem: `FERC eLibrary project snapshot`,
    accession: t,
    docket: e.docket,
    period: r,
    scope: e.project,
    method: `Backend-generated filing classification and grouping`,
    availability: `Present in supplied snapshot`,
    origin: `eLibrary document metadata`,
    validation: `Not independently verified by this frontend`,
    warnings: [
      `No direct source URL or full source body was included in the supplied project export.`,
      `Representative accessions are a selection, not necessarily every filing in the activity group.`,
    ],
  }),
  eU: ChangeItem[] = [
    {
      id: `c1`,
      kind: `archive`,
      domain: `Projects`,
      category: `Grouped project activity`,
      date: `2026-09-08`,
      title: `CP25-10 construction/compliance filing group`,
      entity: `Southeast Supply Enhancement · CP25-10`,
      company: `Company not mapped`,
      regime: `Interstate gas project`,
      explanation: `The supplied snapshot grouped one filing as context-dependent construction/compliance activity. It is retained in the archive and is not promoted to a substantive or economic event.`,
      source: $H(
        QH[0],
        `20260908-3005`,
        `Construction / compliance filing`,
        `2026-09-08`,
      ),
    },
    {
      id: `c2`,
      kind: `substantive`,
      domain: `Projects`,
      category: `Construction / service authorisation`,
      date: `2026-07-22`,
      title: `Construction activities authorised at Hinds and Tallulah compressor stations`,
      entity: `Southeast Compression Utility and Reliability · CP25-219`,
      company: `Company not mapped`,
      regime: `Interstate gas project`,
      explanation: `The supplied milestone describes a letter granting the sponsor’s request to commence specified construction activities.`,
      source: $H(
        QH[1],
        `20260722-3014`,
        `Construction / Service Authorization`,
        `2026-07-22`,
      ),
    },
    {
      id: `c3`,
      kind: `substantive`,
      domain: `Projects`,
      category: `Regulatory decision`,
      date: `2026-06-18`,
      title: `Certificate order recorded for Appalachian Reliability`,
      entity: `Appalachian Reliability · CP25-528`,
      company: `Company not mapped`,
      regime: `Interstate gas project`,
      explanation: `The project snapshot classifies the filing as a regulatory decision and assesses the current stage as Certificate. The stage is filing-based, not a separate formal status field.`,
      source: $H(QH[2], `20260618-3080`, `Regulatory Decision`, `2026-06-18`),
    },
    {
      id: `c4`,
      kind: `substantive`,
      domain: `Projects`,
      category: `Construction / service authorisation`,
      date: `2026-02-25`,
      title: `Southeast Supply Enhancement receives construction authorisation milestone`,
      entity: `Southeast Supply Enhancement · CP25-10`,
      company: `Company not mapped`,
      regime: `Interstate gas project`,
      explanation: `The supplied milestone records a letter granting the 18 February 2026 request to commence construction.`,
      source: $H(
        QH[0],
        `20260225-3042`,
        `Construction / Service Authorization`,
        `2026-02-25`,
      ),
    },
    {
      id: `a1`,
      kind: `archive`,
      domain: `Operating Assets`,
      category: `Periodic filing`,
      date: `2018-04-17`,
      filedDate: `2018-04-17`,
      reportingPeriod: `2017 FY / Q4 construction`,
      title: `Tennessee Gas Pipeline 2017 annual filing`,
      entity: `Tennessee Gas Pipeline system`,
      company: `Kinder Morgan`,
      regime: `Interstate gas`,
      explanation: `One expandable archive item represents the periodic filing and its copied headline values.`,
      source: XH[1].sources.find((e) => e.id === `tgp-2017q4`)!,
      filingChildren: [
        {
          label: `Gas operating revenue`,
          value: `$409.5m · 2017 Q4 derived period`,
        },
        {
          label: `Net utility operating income`,
          value: `$174.5m · 2017 Q4 derived period`,
        },
        { label: `Total throughput`, value: `872.4m Dth · 2017 Q4` },
      ],
    },
    {
      id: `a2`,
      kind: `archive`,
      domain: `Operating Assets`,
      category: `Periodic filing`,
      date: `2018-04-17`,
      filedDate: `2018-04-17`,
      reportingPeriod: `2017 FY`,
      title: `Transco 2017 annual filing`,
      entity: `Transcontinental Gas Pipe Line system`,
      company: `Williams`,
      regime: `Interstate gas`,
      explanation: `Historical filing archive item from the copied reference slice; it is not presented as current news.`,
      source: XH[0].sources.find((e) => e.id === `transco-annual`)!,
      filingChildren: [
        { label: `Gas operating revenue`, value: `$1.789bn · 2017 annual` },
        {
          label: `Net utility operating income`,
          value: `$419.5m · 2017 annual`,
        },
        {
          label: `Quarterly detail`,
          value: `Copied sample ends at 2017 Q3; no Q4 value is derived in the frontend`,
        },
      ],
    },
    {
      id: `r1`,
      kind: `review`,
      domain: `Operating Assets`,
      category: `Reconciliation warning`,
      date: `2022-12-31`,
      reportingPeriod: `2021 Q4`,
      title: `TGP Q4 accounting identity differs by $2`,
      entity: `Tennessee Gas Pipeline system`,
      company: `Kinder Morgan`,
      regime: `Interstate gas`,
      explanation: `The repaired reference package retains the values with a warning. This is a source QA item, not an investor headline.`,
      source: XH[1].sources.find((e) => e.id === `tgp-annual`)!,
    },
    {
      id: `r2`,
      kind: `review`,
      domain: `Projects`,
      category: `Assessment unavailable`,
      date: `2026-09-09`,
      title: `Regulatory outlook unavailable for CP25-219`,
      entity: `Southeast Compression Utility and Reliability · CP25-219`,
      company: `Company not mapped`,
      regime: `Interstate gas project`,
      explanation: `The supplied regulatory_outlook field is null. It does not mean zero open requests or “all clear.”`,
      source: $H(QH[1], ``, `Project snapshot contract`, `2026-09-09`),
    },
  ],
  tU: Record<string, string> = {
    'Filing entity': `The legal entity that submitted the FERC filing. Its figures may not equal a named asset, segment, or parent-company total.`,
    CID: `FERC company identifier used to distinguish filing entities.`,
    Docket: `The FERC proceeding identifier used to group regulatory filings and decisions.`,
    Accession: `An eLibrary document identifier. It may be unavailable for sources outside eLibrary.`,
    MDQ: `Maximum daily quantity covered by the relevant firm transportation contracts; not physical pipeline capacity.`,
    'Top-five shipper share': `The five largest shippers’ combined share on the stated quantity or usage basis; not automatically revenue concentration.`,
    'Primary-term expiry': `The end of a contract’s initial term. Continuation rights and unknown terms remain separate.`,
    'Year-on-year': `A comparison with the same period one year earlier.`,
    'Percentage points': `The arithmetic difference between two percentages, distinct from percent growth.`,
    'Cost of service': `A carrier-reported regulatory cost calculation. Revenue less cost of service is not automatically profit or unlawful over-earning.`,
    'Rate base': `A regulatory input used in cost-of-service calculations; it is not market value.`,
    WACC: `Weighted average cost of capital used as a regulatory input where supplied; not proof of realised return.`,
    'Under review': `Information exists, but a stated interpretation or quality check remains unresolved; this differs from no filing.`,
    'Firm / interruptible': `Service categories with different contractual priority. A firm usage share is not automatically fixed-fee revenue protection.`,
  },
  nU = {
    operating: {
      label: `Operating release`,
      date: `2026-09-08`,
      identity: `operating_assets_all_regimes_REPAIRED_FULL.zip · sha256 2567244938a7645…`,
      note: `This frontend copies a selected Transco/TGP metric slice plus reviewed Elba Express and TransColorado identity/type rows; it does not load the database or full raw cache.`,
    },
    projects: {
      label: `Tommy project snapshots`,
      date: `2026-09-09`,
      identity: `project_view_CP25-10 / CP25-219 / CP25-528`,
      note: `Backend-generated snapshots; representative activity accessions are not the full docket archive.`,
    },
  };
export const operatingAssets = XH;
export const projects = liveProjectsJson as ProjectView[];
const projectSourceBase = $H;
export const projectSource = (
  project: ProjectView,
  accession: string,
  title: string,
  date?: string,
  description?: string,
): SourceDetail => ({
  ...projectSourceBase(project, accession, title, date),
  description,
});
const changeDescriptions: Record<string, string> = {
  c1: 'Construction/compliance activity related to project implementation and compliance.',
  c2: 'Letter granting the 17 July 2026 request to commence specified construction activities at the Hinds and Tallulah Compressor Stations.',
  c3: 'Order issuing a certificate for the Appalachian Reliability Project; the supplied description notes a separate concurring statement.',
  c4: 'Letter granting the 18 February 2026 request to commence construction of the project.',
};
export const changes: ChangeItem[] = eU.map((item) => ({
  ...item,
  source: {
    ...item.source,
    description: changeDescriptions[item.id] ?? item.source.description,
  },
}));
export const glossary: Record<string, string> = tU;
export const sourceProvenance = {
  ...nU,
  operating: {
    ...nU.operating,
    identity:
      'operating_assets_all_regimes_REPAIRED_FULL.zip · sha256 2567244938a7645ba1fe09b81486cf3780cd1a769b61b59afee25a6309f382d5',
  },
};
